services:
  # A web service
  - type: web
    name: college-management-system
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: cd school_management_system && python -m uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: USE_SQLITE_MEMORY
        value: false
      - key: FIRST_SUPERUSER
        value: admin@example.com
      - key: FIRST_SUPERUSER_PASSWORD
        value: admin
      - key: DATABASE_URL
        fromDatabase:
          name: college_management_db
          property: connectionString

databases:
  # A PostgreSQL database
  - name: college_management_db
    plan: free
    ipAllowList: []

Start Command: python -m uvicorn school_management_system.main:app --host 0.0.0.0 --port $PORT

